// Code generated by mockery v2.1.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SwapiRepository is an autogenerated mock type for the SwapiRepository type
type SwapiRepository struct {
	mock.Mock
}

// GetPlanetApparitions provides a mock function with given fields: name
func (_m *SwapiRepository) GetPlanetApparitions(name string) (int32, error) {
	ret := _m.Called(name)

	var r0 int32
	if rf, ok := ret.Get(0).(func(string) int32); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(int32)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
